#==============================================#
# Barrier Zone by RedSMURF: Configuration file #
#==============================================#

# To add a new barrier zone, follow the example below
# [Barrier Zone Name]
# BARRIER_FLAGS                 = a - Active Delay      b - Active Duration

# BARRIER_SPAWN_CHANCE          = Barrier's respawn probability (0.0 = never, 1.0 = always)
# BARRIER_ACTIVE_DELAY          = Delay in seconds before the barrier becomes active at round start
# BARRIER_ACTIVE_DURATION       = Duration of the active state in seconds
# BARRIER_ACTIVE_COOLDOWN       = Cooldown in seconds before the barrier becomes active again

[Main Settings]
SETTING_DEFAULT_MODEL               = models/BarrierZone/star.mdl
SETTING_DEFAULT_FLAGS               = 0
SETTING_DEFAULT_SPAWN_CHANCE        = 1.0
SETTING_DEFAULT_ACTIVE_DELAY        = 5.0 10.0
SETTING_DEFAULT_ACTIVE_DURATION     = 20.0 20.0
SETTING_DEFAULT_ACTIVE_COOLDOWN     = 5.0 5.0

SETTING_BARRIER_LOAD                = 1             # Whether to load saved Barrier Zones data of the current map
SETTING_BARRIER_CHECK               = 10.0          # Maximum selection distance when checking nearby barrier zones
SETTING_BARRIER_TASK                = 0.1           # Time interval in seconds to check for Barrier Zones and apply their effects
SETTING_OFFSET_BASE                 = 90.0          # Default forward offset when previewing Barrier Zone placement
SETTING_OFFSET                      = 42.0 900.0    # Minimum - Maximum offset from the player to the Barrier Zone
SETTING_OFFSET_STEP                 = 10.0          # Step size when scrolling to move Barrier Zone forward/backward
SETTING_GHOST_ALPHA                 = 128           # Transparency level of the ghost preview model (0 - 255)
SETTING_BARRIER_BLOCK_DAMAGE        = 1
SETTING_BARRIER_BOUNCE_PROJECTILES  = 1

SETTING_SIZE_BASE                   = 32.0
SETTING_SIZE_HEIGHT                 = 5.0 1500.0
SETTING_SIZE_WIDTH                  = 5.0 1500.0
SETTING_SIZE_DEPTH                  = 5.0 1500.0

SETTING_BEAM                        = sprites/white.spr
SETTING_BEAM_WIDTH                  = 5
SETTING_BEAM_ALPHA                  = 255
